# Generated by Django 3.1.7 on 2021-03-15 23:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduce nombre de sitio de partida', max_length=50, verbose_name='Lugar de partida')),
            ],
            options={
                'verbose_name': 'autobús',
                'verbose_name_plural': 'Autobuses',
            },
        ),
        migrations.CreateModel(
            name='BestWishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduce tu nombre', max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(help_text='Introduce tu apellido', max_length=50, verbose_name='Apellido')),
                ('message', models.TextField(blank=True, default='', help_text='¡Introduce un mensaje para los novios!', max_length=500, verbose_name='Mensaje')),
                ('accepted', models.BooleanField(blank=True, default=False, help_text='Si es seleccionado el mensaje se mostrara en el apartado de la web.', verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Mensaje para los novios',
                'verbose_name_plural': 'Mensajes para los novios',
            },
        ),
        migrations.CreateModel(
            name='CampeonatoGolf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='p.e Campeonato de Golf', max_length=50, verbose_name='Nombre campeonato')),
                ('description', models.TextField(help_text='Esta es la descripcion que aparecerá debajo del título', max_length=150, verbose_name='Descripcion')),
                ('lugar', models.CharField(help_text='Lugar donde se celebrará', max_length=50, verbose_name='Lugar')),
                ('location_url', models.URLField(blank=True, default='', help_text='Introduce el enlace a google maps', max_length=2000, verbose_name='Enlace a Google Maps')),
                ('fecha', models.DateTimeField(help_text='Introduce la fecha y hora del campeonato', verbose_name='Fecha del campeonato')),
            ],
            options={
                'verbose_name': 'Info Campeonato',
                'verbose_name_plural': 'Campeonato de Golf',
            },
        ),
        migrations.CreateModel(
            name='FechaDeBoda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(help_text='Introduce la fecha y hora de la boda', verbose_name='Fecha de la boda')),
            ],
            options={
                'verbose_name': 'Fecha de la boda',
                'verbose_name_plural': '_Fecha de la boda',
            },
        ),
        migrations.CreateModel(
            name='InscripcionCampeonato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID única asociada al participante', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Introduce tu nombre', max_length=20, verbose_name='Nombre')),
                ('surname', models.CharField(help_text='Introduce tus apellidos', max_length=50, verbose_name='Apellidos')),
                ('handicap', models.DecimalField(decimal_places=2, help_text='Introduce tu handicap', max_digits=4, verbose_name='Handicap')),
                ('licencia', models.CharField(default='', help_text='Introduce tu número de licencia', max_length=12, null=True, verbose_name='Número de licencia')),
            ],
            options={
                'verbose_name': 'inscripción campeonato',
                'verbose_name_plural': 'Inscripciones campeonato',
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduce el nombre del evento (p.e Salida autobus Pamplona)', max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Introduce una descripción para el evento', max_length=1000, verbose_name='Descripción del evento')),
                ('start_time', models.TimeField(help_text='Introduce la hora de inicio', verbose_name='Hora inicio')),
                ('end_time', models.TimeField(blank=True, help_text='Introduce la hora de finalización', null=True, verbose_name='Hora fin')),
                ('location_name', models.CharField(blank=True, help_text='Introduce el nombre de la localización', max_length=50, verbose_name='Nombre localización')),
                ('location_url', models.URLField(blank=True, default='', help_text='Introduce el enlace a google maps', max_length=2000, verbose_name='Enlace a Google Maps')),
                ('image', models.URLField(default='', help_text='Introduce el enlace de la fotografía', max_length=2000, verbose_name='Enlace a la imagen')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'Itinerario',
            },
        ),
        migrations.CreateModel(
            name='ItinerarioHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Este es el texto que aparecerá en la página principal', max_length=20, verbose_name='Nombre header')),
                ('description', models.CharField(help_text='Esta es la descripcion que aparecerá debajo del título en la página principal', max_length=150, verbose_name='Descripcion header')),
            ],
            options={
                'verbose_name': 'Titulo Itinerario',
                'verbose_name_plural': '_Titulo Itinerario',
            },
        ),
        migrations.CreateModel(
            name='LugarDeLaBoda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Este es el texto que aparecerá en la página principal', max_length=20, verbose_name='Lugar de la boda')),
                ('mensaje', models.CharField(help_text='Este es el texto que aparecerá en la página principal p.e."¡Estás invitado a la boda!" ', max_length=100, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Lugar de la boda',
                'verbose_name_plural': '_Lugar de la boda',
            },
        ),
        migrations.CreateModel(
            name='NombresPareja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novio', models.CharField(help_text='Introduce el nombre del novio', max_length=50, verbose_name='Nombre novio')),
                ('novia', models.CharField(help_text='Introduce el nombre de la novia', max_length=50, verbose_name='Nombre novia')),
                ('descripcion_novio', models.TextField(blank=True, default='', help_text='Introduce descripción del novio (déjalo en blanco si no quieres que aparezca nada)', max_length=400, verbose_name='Descripción novio')),
                ('descripcion_novia', models.TextField(blank=True, default='', help_text='Introduce descripción de la novia (déjalo en blanco si no quieres que aparezca nada)', max_length=400, verbose_name='Descripción novia')),
            ],
            options={
                'verbose_name': 'Nombre',
                'verbose_name_plural': '_Nombres pareja',
            },
        ),
        migrations.CreateModel(
            name='SitiosInteres',
            fields=[
                ('site_type', models.CharField(choices=[('h', 'Hotel'), ('r', 'Restaurante'), ('p', 'Peluqueria'), ('s', 'Lugar de interes')], default='', help_text='Escoge el tipo de sitio', max_length=1)),
                ('name', models.CharField(help_text='Introduce el nombre del sitio', max_length=50, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, default='', help_text='Introduce el número del sitio de interés (si tiene)', max_length=12, verbose_name='Teléfono')),
                ('web', models.URLField(help_text='Introduce el enlace a google maps', max_length=2000, verbose_name='Enlace a Google Maps')),
                ('picture', models.URLField(blank=True, help_text='URL de la foto del sitio de interés', max_length=2000, verbose_name='Foto del sitio')),
            ],
            options={
                'verbose_name': 'sitio de interés',
                'verbose_name_plural': 'Sitios de interés',
            },
        ),
        migrations.CreateModel(
            name='WebPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(help_text='Introduce la contraseña para el sitio web', max_length=50, verbose_name='Contraseña')),
                ('is_required', models.BooleanField(default=False, help_text='¿Quieres que la web tenga contraseña?', verbose_name='Activada')),
            ],
            options={
                'verbose_name': 'Contraseña',
                'verbose_name_plural': 'Contraseña Global',
            },
        ),
        migrations.CreateModel(
            name='Confirmacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID única asociada a la confirmación', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Introduce tu nombre', max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(help_text='Introduce tu apellido', max_length=50, verbose_name='Apellido')),
                ('have_a_partner', models.BooleanField(default=False, help_text='¿Traes un acompañante?', verbose_name='Acompañante')),
                ('partner_name', models.CharField(blank=True, default='', help_text='Introduce el nombre del acompañante', max_length=50, verbose_name='Nombre acompañante')),
                ('partner_surname', models.CharField(blank=True, default='', help_text='Introduce el apellido del acompañante', max_length=50, verbose_name='Apellido acompañante')),
                ('bus_service', models.BooleanField(default=False, help_text='¿Necesitas autobús?', verbose_name='Autobús')),
                ('bus_place', models.CharField(blank=True, default='', help_text='Responder sólo si se necesita autobús y estás en el Valle del Baztan', max_length=50, verbose_name='¿En qué hotel te hospedarás?')),
                ('song_name', models.CharField(blank=True, help_text='¡Introduce una canción que quieres que suene durante la fiesta!', max_length=50, null=True, verbose_name='Canción y grupo')),
                ('food_restrictions', models.TextField(blank=True, default='', help_text='Especifica, en caso de tener acompañante, quién tiene la alergia/otro', max_length=500, verbose_name='Alergias alimenticias / Otros')),
                ('bus', models.ForeignKey(blank=True, help_text='Responder sólo si se necesita autobús', null=True, on_delete=django.db.models.deletion.RESTRICT, to='wedding.autobus', verbose_name='Lugar de autobús')),
            ],
            options={
                'verbose_name': 'confirmación',
                'verbose_name_plural': 'Confirmaciones',
            },
        ),
    ]
