# Generated by Django 3.1.5 on 2021-03-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcioncampeonato',
            name='day_pref',
            field=models.CharField(choices=[('m', 'Viernes por la mañana'), ('t', 'Viernes por la tarde'), ('i', 'Me da igual')], default='', help_text='¿Cuándo te viene mejor?', max_length=1, verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='inscripcioncampeonato',
            name='wantToRent',
            field=models.BooleanField(blank=True, default=False, help_text='¿Alquilarías palos?', verbose_name='Palos'),
        ),
    ]
